/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetonumeros;

/**
 *
 * @author Gutho
 */
public class Tela1 extends javax.swing.JFrame {

    /**
     * Creates new form Tela1
     */
    public Tela1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbValor1 = new javax.swing.JLabel();
        tfValor1 = new javax.swing.JTextField();
        lbValor2 = new javax.swing.JLabel();
        tfValor2 = new javax.swing.JTextField();
        lbValor3 = new javax.swing.JLabel();
        tfValor3 = new javax.swing.JTextField();
        lbValor4 = new javax.swing.JLabel();
        tfValor4 = new javax.swing.JTextField();
        lbValor5 = new javax.swing.JLabel();
        tfValor5 = new javax.swing.JTextField();
        lbValor6 = new javax.swing.JLabel();
        tfValor6 = new javax.swing.JTextField();
        lbValor7 = new javax.swing.JLabel();
        tfValor7 = new javax.swing.JTextField();
        lbValor8 = new javax.swing.JLabel();
        tfValor8 = new javax.swing.JTextField();
        btEntra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lbValor1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbValor1.setText("Valor 1:");
        getContentPane().add(lbValor1);
        lbValor1.setBounds(100, 110, 100, 40);

        tfValor1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(tfValor1);
        tfValor1.setBounds(190, 120, 100, 30);

        lbValor2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbValor2.setText("Valor 2:");
        getContentPane().add(lbValor2);
        lbValor2.setBounds(100, 170, 100, 40);

        tfValor2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(tfValor2);
        tfValor2.setBounds(190, 180, 100, 30);

        lbValor3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbValor3.setText("Valor 3:");
        getContentPane().add(lbValor3);
        lbValor3.setBounds(100, 230, 100, 40);

        tfValor3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(tfValor3);
        tfValor3.setBounds(190, 240, 100, 30);

        lbValor4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbValor4.setText("Valor 4:");
        getContentPane().add(lbValor4);
        lbValor4.setBounds(100, 290, 100, 40);

        tfValor4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(tfValor4);
        tfValor4.setBounds(190, 300, 100, 30);

        lbValor5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbValor5.setText("Valor 5:");
        getContentPane().add(lbValor5);
        lbValor5.setBounds(540, 110, 100, 40);

        tfValor5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(tfValor5);
        tfValor5.setBounds(630, 120, 100, 30);

        lbValor6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbValor6.setText("Valor 6:");
        getContentPane().add(lbValor6);
        lbValor6.setBounds(540, 170, 100, 40);

        tfValor6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(tfValor6);
        tfValor6.setBounds(630, 180, 100, 30);

        lbValor7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbValor7.setText("Valor 7:");
        getContentPane().add(lbValor7);
        lbValor7.setBounds(540, 230, 100, 40);

        tfValor7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(tfValor7);
        tfValor7.setBounds(630, 240, 100, 30);

        lbValor8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbValor8.setText("Valor 8:");
        getContentPane().add(lbValor8);
        lbValor8.setBounds(540, 290, 100, 40);

        tfValor8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(tfValor8);
        tfValor8.setBounds(630, 300, 100, 30);

        btEntra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btEntra.setText("Entra");
        getContentPane().add(btEntra);
        btEntra.setBounds(360, 380, 130, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEntra;
    private javax.swing.JLabel lbValor1;
    private javax.swing.JLabel lbValor2;
    private javax.swing.JLabel lbValor3;
    private javax.swing.JLabel lbValor4;
    private javax.swing.JLabel lbValor5;
    private javax.swing.JLabel lbValor6;
    private javax.swing.JLabel lbValor7;
    private javax.swing.JLabel lbValor8;
    private javax.swing.JTextField tfValor1;
    private javax.swing.JTextField tfValor2;
    private javax.swing.JTextField tfValor3;
    private javax.swing.JTextField tfValor4;
    private javax.swing.JTextField tfValor5;
    private javax.swing.JTextField tfValor6;
    private javax.swing.JTextField tfValor7;
    private javax.swing.JTextField tfValor8;
    // End of variables declaration//GEN-END:variables
}
